### ISSUE TITLE
[QA] Need to test reCaptcha functionality and be sure that unique per each session and not cached 

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#102]
TODO:
1. Define expect test scenario, one of the possible examples:
- Caching is enabled(FPC, Varnish, etc)
- Open 1 PDP page(all cachable pages) as a different tab of one browser (and different browsers, private tab, etc)
- Verify-in page sources that reCaptcha block has different code/key etc. and it is not cached

2. If need add Test-Case into HipTest this scenario

**Comment by engcom-Delta** [comment]
Hi @sdzhepa , issue is fixed with FPC.
**Testing scenario:**

- Create simple product
- Enable Rating
- Enable 'reCaptcha v3' for Storefront for 'Product Review':
- - Enable for Product Review = reCAPTCHA v3 Invisible

- Go to Storefront
- Open product details page for Test Simple Product page
- Refresh page to make sure it is cached
- Scroll to the 'Reviews' section
- Fill all required fields and Submit Review
- :heavy_check_mark: New Review successfully submitted
- :heavy_check_mark: No error message is shown
- Fill all required fields and Submit Review again with new data

**Result:**
:heavy_check_mark: New Review successfully submitted with last data
:heavy_check_mark: No error message is shown

**Notice:** Before fix Recaptcha recognized user as bot after second time review was created

**Comment by sdzhepa** [comment]
Not actual anymore
was tested multiple times during several regression cycles
