### ISSUE TITLE
Recaptch badge is not shown on PayPal PayflowPro payment form if 'Invisible Badge Position' is 'Bottom Left/Right'

### ISSUE THREAD

**Issue by VasylShvorak** [magento/securify#204]
### Preconditions (*)

1. Magento with security-package 1.0-develop
2. Simple product is created
3. Payment PayPal PayflowPro is configured

Note: seems it can be repro only if we enable this reCAPCTHA for Login option and PayPal

### Steps to reproduce (*)

1. Configure reCAPTCHA v2 Invisible:
- Enable for Customer Login=reCAPTCHA v2 Invisible
- Enable for PayPal PayflowPro payment form=reCAPTCHA v2 Invisible
- Invisible Badge Position=Bottom Left or Right

2. Add product to cart
3. Go to checkout page
4. On Review & Payments page select **Credit Card (Payflow Pro)** payment method

### Expected result (*)

1. Recaptcha badge is displayed for PayPal PayflowPro payment form

### Actual result (*)

1. Recaptcha badge is not shown for PayPal PayflowPro payment form
![image](https://user-images.githubusercontent.com/26908019/79200220-c6680780-7e3e-11ea-9e86-d40824fa1b19.png)

**Comment by sdzhepa** [comment]
FYI:
@naydav 


Result of investigating for this issue:
- seems this issue is not specific for PayPal reCAPCTHA
- "conflict with enabled  “Enable for Customer Login”". In some cases Inline badge is not shown on Checkout during login even with disabled reCAPCTHA for PayPal. FYI: @engcom-Delta  after fix need to test these flows
- As possible Root Cause Analysis:  fix in https://github.com/magento/security-package/issues/118 leades to the conflict

Thank you @viktym for assistance with this issue

**Comment by viktym** [comment]
When ReCaptcha is enabled for customer login on the checkout page start rendering at once 2 reCaptcha's components (recaptcha-popup-login, recaptcha-checkout-login)
When reCaptcha for PayPal is enabled we have third component rendering ( recaptcha-checkout-paypal-form)
See 
https://github.com/magento/security-package/blob/9d880c01fc3ff3c26b65927db5e37da78cab29da/ReCaptchaCheckout/Block/LayoutProcessor/Checkout/Onepage.php#L53
https://github.com/magento/security-package/blob/7e254a253462e5991e13210dd040d59ea1f4ab69/ReCaptchaCustomer/Plugin/Block/Account/InjectRecaptchaInAuthenticationPopup.php#L63

To observe this behavior put a breakpoint here https://github.com/magento/security-package/blob/0f19528166a367c1bc9388891d50b50f6dc1e924/ReCaptchaFrontendUi/view/frontend/web/js/reCaptcha.js#L122

Somehow these multiple renderings prevent displaying the badge when Position is 'Bottom Left/Right'

When only one reCaptcha renders the badge is visible.
To verify that turn off reCaptcha for customer login (since it renders at once two captchas) and you will be able to see that badge for Paypal reCaptcha.

How to solve this conflict and make badge visible when more than one reCaptcha is rendered  I didn't find out.

**Comment by engcom-Kilo** [comment]
Seems issue by Google reCAPTCHA -
if element of reCAPTCHA (v3, v2 invisible) rendering in hidden block, 
badge will not visible.

**Comment by naydav** [comment]
PR: https://github.com/magento/security-package/pull/237

**Comment by sdzhepa** [comment]
Fixed should be delivered in https://github.com/magento/security-package/pull/248

**Comment by sdzhepa** [comment]
It is duplicate of https://github.com/magento/security-package/issues/224

Initial problem was fixed in https://github.com/magento/security-package/issues/224
this issue its just additional user scenario
