### ISSUE TITLE
Not the best user experience for reCPACTHA with PayPal if user does not check reCAPTHCA

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#207]
### Preconditions (*)

1. ReCaptcha v2(I am not a robot) is configured and enabled for PayPal on Checkout
2.  ![2020-04-15_16-59-36](https://user-images.githubusercontent.com/3409584/79393297-ab7abd80-7f3a-11ea-947d-ab76b9beeddf.png)

### Steps to reproduce (*)
1. Add any product to cart and start checkout
2. Fill all required data on Shipping step and go next
3. Select "Credit Card (Payflow Pro)" payment method 
4. Fill all required payment data
5. DO NOT CHECK reCAPCTHA
6. Click place order

### Actual result (*)
1. A pop-up window with an error message appears for a couple of seconds(2-5) and then the page automatically reloaded. All filed data were removed from fields
See recording for more details: https://www.screencast.com/t/KyNxF3R2c

### Expected result (*)
- This point should be improved
- Entered payment data should not be removed
- Probably we can use JS validation, like "This is a required field" without full page reloading
- or just error message in the red box(as for other errors during checkout) but without page reloading
- not sure that pop-up is the best solution here but at least user should have possibility to read the message and click "OK" or "Cancel" buttons that shown on this pop-up

**Comment by sdzhepa** [comment]
@engcom-Delta  could you please check how it worked on the previous Magento release.
I think can be used composer CE installation.

Just want to know this is something that we broke during our work - like regression bug
or behavior that was previously

**Comment by viktym** [comment]
The issue with disappearing pop-up is caused by https://github.com/magento/magento2/pull/23234 
A couple of weeks ago I had a conversation with the author of this PR @eduard13 and we agreed that it should be reverted. 
` this.options.actions.always();`  must be called after the user click on "Ok" button (not before)
So this line should be inside Magento_Ui/js/modal/confirm::closeModal() like it is in parent JS component  https://github.com/magento/magento2ce/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/modal/confirm.js#L97

Author of https://github.com/magento/magento2/pull/23234  @eduard13 refused to revert his PR due to the lack of time.
@sdzhepa could you create an issue in https://github.com/magento/magento2/ and find someone who is willing to help with reverting this PR. Since it can potentially affect other Magento core functionality as well as 3-rd party extensions.

**Comment by sdzhepa** [comment]
PR https://github.com/magento/magento2/pull/23234 has been reverted.
@engcom-Delta could you please check this flow on the latest code?

**Comment by engcom-Delta** [comment]
@sdzhepa 
I checked this flow and now user have possibility to read the message and click "OK"

Current behavior on the latest code:
**reCAPTCHA v2 ("I am not a robot")**
![Peek 2020-04-22 10-10](https://user-images.githubusercontent.com/51681379/79954441-01dd8400-8486-11ea-9ea8-cd65f15f2a18.gif)

**reCAPTCHA v2 Invisible(with wrong Google API Secret Key)**
![Peek 2020-04-22 10-21](https://user-images.githubusercontent.com/51681379/79954434-ff7b2a00-8485-11ea-9319-63f0479b274c.gif)

**reCAPTCHA v3 Invisible(with wrong Google API Secret Key)**
![Peek 2020-04-22 10-31](https://user-images.githubusercontent.com/51681379/79954425-fb4f0c80-8485-11ea-848a-8804fcc9392c.gif)

**Comment by sdzhepa** [comment]
Thank you @engcom-Delta 

We can close this issue
