### ISSUE TITLE
Magento 2.3.1 ReCaptcha error on checkout with virtual products

### ISSUE THREAD

**Issue by aleingargiola** [magento/securify#24]
I'm working on Magento 2.3.1 version. And enabled Google ReCaptcha v2

The error you can see in the attachment file happens when a "not logged in" user with only virtual products in his cart goes to checkout.

In this situation the checkout appears a little bit different, because the virtual product doesn't need the first checkout step (shipping step) info.

If user fills email field with an already registered customer email, Magento "knows" the user is a registered customer email and adds the password field for login.
But ReCaptcha field doesn't appear. So when the customer clicks on Login button Magento shows the error message: Incorrect reCaptcha.

This is a serious problem for merchant that have only virtual products.

Can you fix it?
Thanks

![Schermata 2019-07-05 alle 18 48 23](https://user-images.githubusercontent.com/49201676/60735941-87269500-9f55-11e9-9a0d-0547f8aab167.png)

**Comment by sdzhepa** [comment]
Due to significant refactoring and UI changes in Admin Panel for reCAPCTHA module in the scope of security-package for 2.4.x release, this bug is not actual anymore.

1. This case was fixed and should be delivered with "msp/recaptcha" version `2.2.3` for 2.3.5+ Magento releases
2. This case was fixe and verified for `security-package` and should be a part of the next 2.4.x release of Magento
