### ISSUE TITLE
Admin user 2FA provider preference not saving

### ISSUE THREAD

**Issue by hunterallen** [magento/securify#295]
### Preconditions (*)

1. Magento 2.4.2
2. Authy and U2F 2FA providers enabled

### Steps to reproduce (*)

1. Enable Authy and U2F in Stores > Configuration > Security > 2FA
2. Login to admin without U2F key

### Expected result (*)

1. Expected to be prompted with users default 2FA option.

### Actual result (*)

1. Users without U2F key prompted to re-configure Two-Factor Authorization.
<img width="464" alt="2fa" src="https://user-images.githubusercontent.com/26381144/114731183-87011f00-9d0f-11eb-9f82-62e482a4dc9e.png">

After re-configuring Two-Factor Authorization, users are redirected to the admin dashboard as expected. 
Once the user logs out and attempts to log in again, the cycle repeats.

### Additional Information

Database table "tfa_user_config" is saving the users "default_provider" correctly (either Authy or u2fkey).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nathanjosiah** [comment]
Hello @hunterallen! This is something that our team has been discussing just recently in various forms. The summary of the conversations is this is currently correct behavior although it isn't ideal and we would like to address it at some point. 

You are only required to enable one of the supported providers and once they are configured only one is required to sign in. However, you will continue to be prompted to configure each of them until all required providers are configured. We had a very tight schedule and limited resources to completely rebuild and redocument all of 2FA so not everything all the features that we wanted were able to be implemented.

Having said that, I am not opposed to adding the ability to support more flexible options for 2FA providers so long as one is always required and configured. But this would require some planning and new designs since the current design would prevent you from configuring more than one provider if we made some optional. The biggest factor here is we don't have the bandwidth to support any feature development for 2FA right now. 

If you would like to make a proposal for us to consider we could review that along with an associate PR if you would like.

**Comment by amansilla** [comment]
I have the same issue, after inserting the yubikey you get access to the backend but the connection is not persisted so it can be reused in further connections. Every time you login into the backend you've to get the Magento email and reconfigure it every time.
