### ISSUE TITLE
Disable 2fa auth for specifi user

### ISSUE THREAD

**Issue by ghost** [magento/securify#304]
Hello,

Is it possible to disable 2fa for specific user?

Exemple: api user.

Thank you.

**Comment by nathanjosiah** [comment]
Integration users do not require 2fa because they do not authenticate using username/password but rather with a from the admin. If the web api user needs to get a token using a username/password then 2fa is required by definition because otherwise it is a pointless feature and the web api could be used to bypass the mechanism.
