### ISSUE TITLE
The Magento works with Google reCaptcha v3 incorrectly.

### ISSUE THREAD

**Issue by andrewbess** [magento/securify#329]
### Preconditions (*)

1. Magento 2.4.5-p1, Magento 2.4.6 (We didn't test it in other versions)
2. Setup Google reCaptcha v3 in store configuration

### Steps to reproduce (*)

1. Setup `Minimum Score Threshold` to "1.0"
2. Setup enabling reCaptcha for necessary forms in "Storefront" tab
3. Try to submit form on storefront

### Expected result (*)

1. Google reCaptcha shows popup with reCaptcha challenge
<img width="940" alt="recaptcha-expected-resilt" src="https://user-images.githubusercontent.com/10788564/229443923-7887c43b-d57c-43fd-8b84-807460ee3ebe.png">

### Actual result (*)

1. The system doesn't show popup with Google reCaptcha challenge
<img width="1388" alt="recaptcha-actual-result" src="https://user-images.githubusercontent.com/10788564/229444016-768a0fa6-dccb-42fa-b454-9248c07a97b7.png">

**Comment by fredden** [comment]
@andrewbess as far as I know, Google reCAPTCHA v3 does not provide any opportunity for a human to prove they are not a robot. v3 provides a score to the application, which Magento transforms into a boolean. See https://github.com/magento/merchdocs/pull/1597 / https://github.com/magento/security-package/issues/319

It sounds like you want to use v2 so that a (client-side) challenge is presented to users with a low score. The extensions in this repository are working as designed.

**Comment by andrewbess** [comment]
> @andrewbess as far as I know, Google reCAPTCHA v3 does not provide any opportunity for a human to prove they are not a robot. v3 provides a score to the application, which Magento transforms into a boolean. See [magento/merchdocs#1597](https://github.com/magento/merchdocs/pull/1597) / #319
> 
> It sounds like you want to use v2 so that a (client-side) challenge is presented to users with a low score. The extensions in this repository are working as designed.

Thank you @fredden for your answer.
